apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "{{TimeStamp}}"
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: nginx
        image: {{IMAGE}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always